server:
    port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
spring:
    application:
      name: hello-config-service
spring.cloud.config.server.git.uri: C:\Users\haris\Downloads\demoOne\LocalRepoForConfigSever